name = "serverless-ecommerce"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "etalase"
database_id = "local-db-id"

[[r2_buckets]]
binding = "R2etalase"
bucket_name = "etalase"
